//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class alphaReportEntities : DbContext
    {
        public alphaReportEntities()
            : base("name=alphaReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnswerForm> AnswerForm { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientContact> ClientContact { get; set; }
        public virtual DbSet<CodeAnswerForm> CodeAnswerForm { get; set; }
        public virtual DbSet<CodeForm> CodeForm { get; set; }
        public virtual DbSet<CodeProject> CodeProject { get; set; }
        public virtual DbSet<CodeProjectDocument> CodeProjectDocument { get; set; }
        public virtual DbSet<CodeProjectUser> CodeProjectUser { get; set; }
        public virtual DbSet<CodeReport> CodeReport { get; set; }
        public virtual DbSet<FormQuestion> FormQuestion { get; set; }
        public virtual DbSet<ItemReport> ItemReport { get; set; }
        public virtual DbSet<ObstacleCategory> ObstacleCategory { get; set; }
        public virtual DbSet<ObstacleReport> ObstacleReport { get; set; }
        public virtual DbSet<ProgressReport> ProgressReport { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<RequestForInformation> RequestForInformation { get; set; }
        public virtual DbSet<RequestForInformationAnswer> RequestForInformationAnswer { get; set; }
        public virtual DbSet<StatusReport> StatusReport { get; set; }
        public virtual DbSet<StatusReportImage> StatusReportImage { get; set; }
        public virtual DbSet<Tool> Tool { get; set; }
        public virtual DbSet<ToolReport> ToolReport { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<UserPosition> UserPosition { get; set; }
        public virtual DbSet<WeatherReport> WeatherReport { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<WorkerReport> WorkerReport { get; set; }
    }
}
