//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerForm
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public string Answer { get; set; }
        public string Note { get; set; }
        public int CodeAnswerFormId { get; set; }
    
        public virtual CodeAnswerForm CodeAnswerForm { get; set; }
        public virtual FormQuestion FormQuestion { get; set; }
    }
}
