//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeProjectUser
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CodeProjectId { get; set; }
        public int Position { get; set; }
    
        public virtual CodeProject CodeProject { get; set; }
        public virtual User User { get; set; }
    }
}
