//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusReportImage
    {
        public int Id { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual StatusReport StatusReport { get; set; }
    }
}
