//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherReport
    {
        public int Id { get; set; }
        public int WeatherId { get; set; }
        public System.TimeSpan Time { get; set; }
        public byte IsDelete { get; set; }
        public Nullable<int> CodeReportId { get; set; }
    
        public virtual CodeReport CodeReport { get; set; }
    }
}
